import React from "react";
import Sales from "./Sales";
import SalesByCategory from "@/components/salesBoxes/SalesByCategory";
/*
//////////////////////////////////////////////////////////

1) Product Category Sales Distribution:
	- Chart: Bar chart
	- Data Source: Products and Orders
	- Display: 
			Show the distribution of 
			sales across different product categories. 
			Each bar represents the percentage 
			or total revenue generated by each category. 
			Identify which categories are 
			the most popular among customers.
	- Formatting:
			Share the workload between front and back.
			Get the all the sales by category from
			the back and reduce all values to their
			totals on the front.

//////////////////////////////////////////////////////////

2) Monthly Revenue Trend:
	- Chart: Line chart
	- Data Source: Orders and Order Date
	- Display: 
			Plot the monthly revenue over a 
			specific period. This chart provides 
			insights into how sales are trending 
			over time. It can reveal seasonal 
			patterns and help in forecasting.

//////////////////////////////////////////////////////////

3) Top Selling Products:
	- Grid: Table with sorting and filtering options
	- Data Source: Products and Orders
	- Display: 
			Display a list of top-selling 
			products along with their sales quantities 
			and revenue. Allow users to sort the table 
			by different metrics. This helps identify 
			the most popular products and their 
			contribution to revenue.

//////////////////////////////////////////////////////////

4) Customer Reviews and Ratings Analysis:
	- Chart: Histogram or bar chart
	- Data Source: Reviews and Ratings
	- Display: 
			Analyze customer reviews and ratings 
			for products. Plot a histogram or bar chart 
			to visualize the distribution of ratings. 
			This can help assess customer satisfaction 
			and the impact of reviews on product sales.

//////////////////////////////////////////////////////////
*/
const components = {
  j: <SalesByCategory gridArea="j" isAboveMediumScreens={true} />,
  //k: <Orders gridArea="k"/>,
  //l: <Products gridArea="l"/>,
  //m: </>,
};

const SalesDashboard = () => {
  return <SalesByCategory gridArea="j" isAboveMediumScreens={true} />;
};

export default SalesDashboard;
